### ISSUE TITLE
企业彩云 - IMAP 邮箱长时间不能接收到邮件

### ISSUE THREAD

**Issue by zhuminling** [ECCloud/AndroidClient#100]
同事的手机，IMAP 邮箱长时间接收不到邮件，请分析日志看看是什么原因。
怀疑是他在电脑上开启了Outlook 通过 IMAP协议同步邮件，手机客户端无法同时登录引起的。但是IMAP 服务端是否有反馈提示信息？是否能给出“用户友好”的提示信息？（日志请查看邮箱）

**Comment by cowmax** [comment]
根据IMAP 服务端核查结果，问题可能是：用户密码错误的情况下，频繁重复登录IMAP 邮箱，IMAP邮箱对客户端地址进行了限制（15分钟）。

注意：同一基站小区内的用户，用户手机上网的IP 地址可能相同，客户端需要防止“密码错误”的情况下，频繁重复登录IMAP服务器。

此问题已经另起新问题进行跟进。
