### ISSUE TITLE
企业彩云 - 关于增加系统菜单入口的需求

### ISSUE THREAD

**Issue by zhuminling** [ECCloud/AndroidClient#107]
由于三星S5、Note3 等手机的“菜单”键重新定义，用户使用手机的“菜单”键无法打开客户端的系统菜单，为解决此问题，参考微信等应用，在客户端的我的应用和应用中心右上方增加系统菜单入口（按钮）

**Comment by cowmax** [comment]
用户点击“系统菜单”按钮之后，系统菜单应该出现在按钮下方。
