### ISSUE TITLE
企业彩云-新邮件接收数量问题

### ISSUE THREAD

**Issue by zhuminling** [ECCloud/AndroidClient#122]
在使用企业彩云客户端接收邮件时，看到系统通知栏有几十封新邮件的到达通知，打开客户端，看到分类栏上的新邮件数量也是几十封新邮件。但是消息列表里并没有那么多新邮件。
      是否我们客户端修改接收邮件逻辑后，导致这个统计有有问题？请核查问题原因。（请根据邮件中的日志排查原因）

**Comment by cowmax** [comment]
新版本客户端上增加了相应的日志，但是目前还没有什么时展。
