### ISSUE TITLE
IMAP邮箱的邮件删除功能优化

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#39]
1. 删除邮件时，提示用户“是否删除”，同时增加选项“从服务器删除”（缺省不选中）
2. 用户可以在系统设置中的邮箱设置里修改此选项

**Comment by zhuminling** [comment]
实现邮件的异步删除
![08-29-10-12-36](https://cloud.githubusercontent.com/assets/7833881/4085971/11c9c896-2f29-11e4-8f05-031ac40eb6e8.png)
