### ISSUE TITLE
IMAP邮箱应用跳转到消息中心/我的邮箱时闪烁

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#41]
从应用中心的“新OA邮箱”应用跳转到“消息中心/我的邮箱”时发生多次闪烁（中间出现空白界面，用户体验较差

**Comment by cowmax** [comment]
应用图标 -- > 我的办公 --> 我的邮箱
导致闪烁。

**Comment by zhuminling** [comment]
用户首次从邮箱应用跳转到我的邮箱，闪烁一次后，不会再闪烁了
