### ISSUE TITLE
通过桌面图标恢复客户端到前端时消息详情界面关闭

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#44]
例如：
1. 启动客户端 -> 消息中心 -> 打开待办公文详情
2. 按手机Home 键，客户端退到后台
3. 点击手机桌面上的应用图标，重新打开客户端
4. 客户端打开之后，界面为消息中心，而原打开的待办公文详情关闭了

同样的问题，也存在于打开某一个应用（应用容器），退到后台，再通过应用图标打开时，应用界面也会被关闭。

**Comment by lvchaoqiang** [comment]
1.6.50_beta06版本已经修改。
