### ISSUE TITLE
IMAP邮箱打开某类型邮件详情立即返回

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#71]
![screenshot_2014-05-22-01-18-34](https://cloud.githubusercontent.com/assets/7324595/3049560/b49b4bf0-e161-11e3-872a-c9fce96c1608.png)
EMC 的一个会议邀请邮件
（1） 点击邮件
（2）立即返回，并提示“打开邮件详情失败”

**Comment by zhuminling** [comment]
已经记录在问题跟踪列表了，还在进行排期
