### ISSUE TITLE
IMAP邮箱邮的邮件列表接收效率问题

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#74]
（1）手动刷新：下拉邮件列表、点击右上角的刷新按钮；
（2）后台服务定时刷新：时间间隔与OA公文保持一致，但是接收时间要错开，避免产生较大的并发流量；
（3）客户端界面切换触发刷新请求；（定义为“手动刷新”的一种）
（4）客户端界面从后端切换到前端触发刷新请求；（定义为“手动刷新”的一种）

说明：
A）允许短时间间隔内发起“手动刷新”请求：只要前一次手动刷新请求、或者后台服务定时查收请求结束，即可以发起“手动刷新”请求；
B）同一时间内，客户端只执行一个“刷新”请求；

**Comment by zhuminling** [comment]
（1）手动刷新：下拉邮件列表、点击右上角的刷新按钮；（现在的邮箱界面右上角是新建邮件按钮，到时候要添加批量删除按钮，建议不要右上角的刷新按钮，只下拉刷新）
