### ISSUE TITLE
IMAP邮箱的邮件标题乱码问题

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#81]
（1）使用 iPhone 客户端接收到邮件（正常）
（2）使用 iPhone  客户端回复邮件
（3）使用Android 客户端接收邮件
（4）邮件标题显示为乱码（MINE 编码）

“乱码”样例如下：
Subject: Re:Re:=?utf-8?Q?Re=3ARe=3A=E4=BC=81=E4=B8=9A=E5=BD=A9=E4=BA=91=E6=8A=95=E8=B5=84=E6=9D=90=E6=96=99=E5=87=86=E5=A4=87?=

**Comment by lvchaoqiang** [comment]
已经5月28发的1.6.50_beta06版本中修复解决。
