### ISSUE TITLE
IMAP邮箱的邮件编辑界面联系人输入实时提示功能

### ISSUE THREAD

**Issue by cowmax** [ECCloud/AndroidClient#87]
IMAP邮箱的邮件编辑界面联系人输入时，实时提示用户输入字符串与企业通讯录、本地通讯录、最近联系人匹配的完整联系人；

**Comment by zhuminling** [comment]
已经记录下来，正在排期中

**Comment by cowmax** [comment]
1. 邮件地址输入自动提示功能的完善：
    2.1. 创建往来邮件地址数据库，包括接受到的邮件的所有邮件地址，发送的所有邮件地址记录，自动提示时优先匹配“往来邮件”，数据按时间降序排列，即“较新”的邮件地址排在前面。
    2.2. 在“往来邮件地址数据”中标识“常用邮件地址”，自动提示时，常用邮件地址排在最前面。
    2.3. 用户手工输入的邮件地址，自动转换为“往来邮件地址”、“企业通讯录”中相应的显示名称，
    2.3. 修正目前“邮件地址输入自动提示”界面上存在的小问题。
